[workspace]
authors = ["Suma Ambati <ambatisuma620@hgmail.com>"]
channels = ["conda-forge"]
name = "assignment 4"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.5,<3.14"
