[workspace]
channels = ["conda-forge"]
name = "assignment 3"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
numpy = ">=2.3.1,<3"
matplotlib = ">=3.10.3,<4"
scikit-learn = ">=1.7.0,<2"
jupyter = ">=1.1.1,<2"
notebook = ">=7.4.4,<8"
ipykernel = ">=6.29.5,<7"
