[workspace]
channels = ["conda-forge"]
name = "Lab2 (1)"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
scikit-learn = ">=1.6.1,<2"
seaborn = ">=0.13.2,<0.14"
ipykernel = ">=6.29.5,<7"
